name: Full Stack Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Lint Backend Code
        run: |
          cd backend
          npm run lint

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Lint Frontend Code
        run: |
          cd frontend
          npm run eslint

      - name: Build and Deploy FullStack
        run: |
          cd backend
          npm run deploy:full
      - name: See Fly Logs
        run: |
          cd backend
          npm run logs:prod
